### PR TITLE
Bootstrap Integration (Staff Dashboard View & Application Template Show)

### PR DESCRIPTION
**Pull request by enragednuke**
Recreation of the #199 PR with no merge conflicts (it was very far behind and with the dumb 'database wiping' incident over spring break, it was easier just to recreate the branch in its entirety and just push this).

Still need to move the CSS to the other fields on the page, will comment again when that is done. Feel free to scan the code until then to make sure I didn't accidentally delete something wrongly during merge conflicts.

*Disclaimer*: There will likely be a side-effect of making other forms look very whacky until they're suited up with Bootstrap elements. @dfaulken said not to try and modify every page in one gigantic PR, so here's the first tidbit of it. Once this is merged, I'll work on getting the other views set up (so the addition of bootstrap doesn't appear in every PR).

### CODE REVIEW

**Comment by enragednuke** [comment]
All good now, here's what the changes look like on my local machine (**note**: this is a series of 4 images, so the scaling might change as you scroll, it's not a weird quirk in the CSS lol)

screen shot 2016-03-29 at 4 54 08 pm
screen shot 2016-03-29 at 4 54 53 pm
screen shot 2016-03-29 at 4 55 22 pm
screen shot 2016-03-29 at 4 55 47 pm

**Comment by Anbranin** [comment]
This looks lovely.
:sparkles: :bouquet: :sparkles:

**Comment by dfaulken** [comment]
Right, so since this process is going to come over the course of incremental PRs, this PR should be against a branch that isn't master, so that we can review and merge changes incrementally without messing up existing views that you haven't gotten to yet in production.

**Comment by dfaulken** [comment]
Also, please no one delete this branch

**Comment by enragednuke** [comment]
Is there a reason to keep it? I already pushed the new PR.

**Pull request closed without merging**
