### PR TITLE
Expect Flash Message

### LINKED ISSUE #192: Use expect_flash_message for integration tests
Completely forgot about this helper method - it's nice not only to make sure that a method is there, but that it's being taken from the YML file.

### PR DESCRIPTION
**Pull request by akaplo**
Closes #192.  

Updated all integration tests to use the spec_helper method ```expect_flash_message``` for...well...expecting flash messages.  

Note that error messages remain unchanged, because they are rendered by a private ApplicationController method called ```show_errors```, and figuring out how to test for it has been determined to be out of the scope of this issue by @dfaulken.

### CODE REVIEW

**Comment by dfaulken** [comment]
Are there any controller tests where we could've used `expect_flash_message`?

**Comment by akaplo** [comment]
Yes, there are plenty!  I thought #192 was just concerned with the current bunch of integration tests.

**Comment by dfaulken** [comment]
Nope, my bad that that wasn't clear. Any place where we manually inspect the `flash` for its `message` content, it'd be better to replace it with the spec helper method - this includes controller tests.

**Comment by akaplo** [comment]
No worries.  I'll change the controller tests tomorrow and update this PR then.

**Comment by akaplo** [comment]
I lied yesterday when I said there are plenty of controller tests to change over.

All that I can find that weren't testing for flash **errors** are already using `expect_flash_message`

**Comment by dfaulken** [comment]
Great, I'll look this over again but it should be good to go.

**Pull request merged**
