### PR TITLE
Remove datetime pickers

### LINKED ISSUE #484: Remove datetimepicker
We've been moving away from datepickers, it would be nice to drop this dependency

Also, datetimepicker is the only reason this app requires moment.js as well.

### PR DESCRIPTION
**Pull request by werebus**
Closes #484

### CODE REVIEW

**Comment by dirschn** [comment]
> frothedoatmilk says...

https://github.com/umts/jobapps/pull/545 run the rake task in this PR

**Comment by frothedoatmilk** [comment]
We shouldn't need to run a rake task after resetting the DB, it should just work.™ Some light substitution was all that was needed #550

**Comment by werebus** [comment]
Seeds are fixed in another PR (#547) — the same PR that removes the rake task that also fixes your problem.

**Review by frothedoatmilk — APPROVED** [review]
In that case

**Comment by werebus** [comment]
> One last thing: https://github.com/umts/jobapps/blob/main/spec/system/viewing_past_applications_table_spec.rb#L7 Not sure if you want to change this spec? It still works but the formatting of the input is definitely not necessary

Well, at the very least the comment is wrong (`:db` is Y-m-d).

**Comment by frothedoatmilk** [comment]
Then it should probably be removed, since the specs will run without it now

**Comment by frothedoatmilk** [comment]
I meant also the `to_formatted_s`, no reason to call it and could be confusing later

**Review by frothedoatmilk — APPROVED** [review]

**Pull request merged**
