### PR TITLE
Upgrade Rails to 7.0

### PR DESCRIPTION
**Pull request by werebus**

### CODE REVIEW

**Comment by werebus** [comment]
Codeclimate issues addressed in #553

**Comment by werebus** [comment]
https://github.com/umts/jobapps/pull/552/files/1d51b7eb4442c07de3c01bd505e8e1babf6503fd to see the changes without the already-reviewed ones in #553

**Review by dirschn — COMMENTED** [review]
What's up with the switch to double quotes?

**Comment by dirschn** [comment]
Oh, looks like that's from the app:update task?

**Review by dirschn — APPROVED** [review]

**Comment by werebus** [comment]
> Oh, looks like that's from the app:update task?

Yeah, at one point "someone" switched them all to single-quotes. But, that someone now thinks that it makes more sense not to have meaningless differences between Rails' default version and ours because then _future_ updates will be easier (`git diff` will show actual differences between our config and the default)

**Pull request merged**
